# Generated by Django 5.1.1 on 2024-09-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['uuid', 'slug'], name='shop_produc_uuid_a5c7dd_idx'),
        ),
    ]
